name: example
description: Example on Sliver Fab.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliver_fab:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - img.jpg
