name: sliver_fab
description: A wrapper widget allowing to use FloatingActionButton on the edge of FlexibleSpacebar
version: 0.0.1
author: Marcin Szalek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/sliver_fab

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
