name: sliver_fab
description: A wrapper widget allowing to use FloatingActionButton on the edge of FlexibleSpacebar
version: 0.1.1
author: Marcin Szalek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/sliver_fab

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
